dataset: 'tumrgbd'
project_name: "Point_SLAM_tumrgbd"
model:
  encode_rel_pos_in_col: False
tracking:
  separate_LR: False
  pixels: 5000
  iters: 200
  vis_inside_freq: 200
  sample_with_color_grad: True
mapping:
  every_frame: 2
  vis_freq: 40
  ckpt_freq: 1000
  mapping_window_size: 10
  pixels: 10000
  iters_first: 500
  geo_iter_first: 200
  iters: 150
  lazy_start: 20
cam:  #NOTE: intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  png_depth_scale: 5000.0
meshing:
  eval_rec: False